//! Local HTTP test server (spec §51, §216, §217).
//!
//! Deterministic file content: bytes for `/<name>` are generated by a
//! counter-based ChaCha8 PRNG seeded from the name+size, so range requests
//! return exactly the same bytes as a full download, across process restarts.
//! Tests can therefore verify SHA-256 end-to-end without any network access.

use axum::body::{Body, Bytes};
use axum::extract::{Path, Query, State};
use axum::http::{header, HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::Router;
use futures_util::stream::Stream;
use rand_chacha::rand_core::{RngCore, SeedableRng};
use rand_chacha::ChaCha8Rng;
use sha2::{Digest, Sha256};
use std::pin::Pin;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::task::{Context, Poll};
use std::time::Duration;

/// Lenient bool parsing: accept `1`/`0`/`true`/`false` (serde_urlencoded
/// only accepts `true`/`false`, which trips up `?no_range=1` style usage).
fn de_bool<'de, D>(d: D) -> Result<Option<bool>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    use serde::Deserialize;
    let s = Option::<String>::deserialize(d)?;
    Ok(match s.as_deref() {
        None | Some("") => None,
        Some("1") | Some("true") | Some("yes") | Some("on") => Some(true),
        Some("0") | Some("false") | Some("no") | Some("off") => Some(false),
        Some(other) => {
            return Err(serde::de::Error::custom(format!("invalid bool value: {other}")))
        }
    })
}

/// Query parameters understood by the test server.
#[derive(serde::Deserialize, serde::Serialize, Default, Clone)]
pub struct Q {
    /// Serve the whole body ignoring Range (no range support).
    #[serde(default, deserialize_with = "de_bool")]
    pub no_range: Option<bool>,
    /// Throttle to N bytes/second.
    pub slow: Option<u64>,
    /// Close the connection after N bytes sent.
    pub fail_after: Option<u64>,
    /// Return this HTTP status instead of the file (404/429/500/503...).
    pub status: Option<u16>,
    /// Retry-After header value (seconds) when status is set.
    pub retry_after: Option<u64>,
    /// Serve chunked (no Content-Length).
    #[serde(default, deserialize_with = "de_bool")]
    pub chunked: Option<bool>,
    /// Send a wrong Content-Range for range requests.
    #[serde(default, deserialize_with = "de_bool")]
    pub wrong_range: Option<bool>,
    /// Send more bytes than the requested range.
    #[serde(default, deserialize_with = "de_bool")]
    pub over_send: Option<bool>,
    /// Require HTTP Basic auth (user:pass).
    #[serde(default, deserialize_with = "de_bool")]
    pub auth: Option<bool>,
    /// Change the content+ETag on every request.
    #[serde(default, deserialize_with = "de_bool")]
    pub change: Option<bool>,
    /// Send fewer bytes than Content-Length claims.
    #[serde(default, deserialize_with = "de_bool")]
    pub truncate: Option<bool>,
    /// Disposition filename override.
    pub filename: Option<String>,
    /// Fail the first request with this status, then succeed (retry tests).
    pub fail_first: Option<u16>,
}

#[derive(Clone)]
pub struct ServerState {
    /// Incremented on every request to a `change` path.
    pub change_counter: Arc<AtomicU64>,
    /// Total requests served.
    pub request_count: Arc<AtomicU64>,
    /// Per-path hit counts (used by `fail_first`).
    pub hits: Arc<std::sync::Mutex<std::collections::HashMap<String, u64>>>,
}

impl ServerState {
    pub fn record_hit(&self, key: &str) -> u64 {
        let mut m = self.hits.lock().unwrap();
        let n = m.entry(key.to_string()).or_insert(0);
        *n += 1;
        *n
    }
}

pub struct Running {
    pub base_url: String,
    pub state: ServerState,
}

/// Start the test server on an ephemeral 127.0.0.1 port. Returns the base URL.
pub async fn start() -> Running {
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .expect("bind test server");
    let addr = listener.local_addr().unwrap();
    let state = ServerState {
        change_counter: Arc::new(AtomicU64::new(0)),
        request_count: Arc::new(AtomicU64::new(0)),
        hits: Arc::new(std::sync::Mutex::new(std::collections::HashMap::new())),
    };
    let app = router(state.clone());
    tokio::spawn(async move {
        axum::serve(listener, app).await.expect("serve");
    });
    Running {
        base_url: format!("http://{addr}"),
        state,
    }
}

pub fn router(state: ServerState) -> Router {
    Router::new()
        .route("/", get(index))
        .route("/hash/{name}", get(file_hash))
        .route("/file/{name}", get(get_file))
        .route("/no-head/{name}", get(get_file).head(reject_head))
        .route("/redirect/{n}", get(redirect))
        .route("/redirect-loop", get(redirect_loop))
        .with_state(state)
}

async fn index() -> &'static str {
    "LDM test server: GET /file/<name>?<opts>, /hash/<name>?<opts>, /redirect/<n>, /redirect-loop"
}

async fn reject_head() -> StatusCode {
    StatusCode::METHOD_NOT_ALLOWED
}

// ---------------------------------------------------------------------------
// Content generation
// ---------------------------------------------------------------------------

/// FNV-1a 64-bit hash.
pub fn fnv1a64(s: &str) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for b in s.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

/// Seed for a file: hash of name + size + extra (change counter).
fn seed_for(name: &str, size: u64, extra: u64) -> [u8; 32] {
    let h = fnv1a64(&format!("{name}:{size}:{extra}"));
    let h2 = fnv1a64(&format!("{name}:{size}:{extra}:second"));
    let mut seed = [0u8; 32];
    seed[..8].copy_from_slice(&h.to_le_bytes());
    seed[8..16].copy_from_slice(&h2.to_le_bytes());
    seed[16..24].copy_from_slice(&(h ^ h2).to_le_bytes());
    seed[24..32].copy_from_slice(&(!h).to_le_bytes());
    seed
}

/// Size of a named fixture: `N` bytes when the name parses as `{N}b`,
/// otherwise fixed defaults. Names: "small" (1 MB), "medium" (8 MB),
/// "large" (64 MB).
pub fn fixture_size(name: &str) -> u64 {
    // `{N}b`, `{N}kb`, `{N}mb`, `{N}gb` (case-insensitive) → bytes.
    let stem = name.split('.').next().unwrap_or(name);
    let lower = stem.to_ascii_lowercase();
    let (num, mult) = if let Some(n) = lower.strip_suffix("gb") {
        (n, 1u64 << 30)
    } else if let Some(n) = lower.strip_suffix("mb") {
        (n, 1u64 << 20)
    } else if let Some(n) = lower.strip_suffix("kb") {
        (n, 1u64 << 10)
    } else if let Some(n) = lower.strip_suffix('b') {
        (n, 1u64)
    } else {
        ("", 0)
    };
    if !num.is_empty() {
        if let Ok(n) = num.parse::<u64>() {
            return n.saturating_mul(mult);
        }
    }
    match stem {
        "small" => 1024 * 1024,
        "medium" => 8 * 1024 * 1024,
        "large" => 64 * 1024 * 1024,
        "empty" => 0,
        _ => 256 * 1024,
    }
}

/// ETag for a file identity.
pub fn etag_for(name: &str, size: u64, extra: u64) -> String {
    format!("\"{:016x}\"", seed_for(name, size, extra)[..8].iter().map(|b| *b as u16).sum::<u16>())
}

/// Stream of deterministic bytes `[start, end)` (inclusive end optional).
pub struct ContentStream {
    rng: ChaCha8Rng,
    pos: u64,
    /// First byte of the requested range (used for relative truncation).
    req_start: u64,
    end: u64,
    chunk: usize,
    /// Slow mode: bytes per second (0 = unlimited).
    rate: u64,
    /// Fail after N bytes (0 = never).
    fail_after: u64,
    sent: u64,
    truncated: bool,
}

impl ContentStream {
    pub fn new(name: &str, size: u64, extra: u64, start: u64, end: Option<u64>, q: &Q) -> Self {
        let mut rng = ChaCha8Rng::from_seed(seed_for(name, size, extra));
        // Seek the counter to `start` (ChaCha words are 4 bytes).
        rng.set_word_pos(start as u128 / 4);
        let skip = (start % 4) as usize;
        if skip > 0 {
            let mut tmp = [0u8; 4];
            rng.fill_bytes(&mut tmp);
        }
        let end = end.unwrap_or(size).min(size);
        // Pace slow streams: chunk size chosen so each chunk takes ≤ ~20ms.
        let rate = q.slow.unwrap_or(0);
        let chunk = if rate > 0 {
            ((rate / 50).max(4 * 1024) as usize).min(64 * 1024)
        } else {
            64 * 1024
        };
        Self {
            rng,
            pos: start,
            req_start: start,
            end,
            chunk,
            rate,
            fail_after: q.fail_after.unwrap_or(0),
            sent: 0,
            truncated: q.truncate.unwrap_or(false),
        }
    }

    pub fn full(name: &str, size: u64, extra: u64, q: &Q) -> Self {
        Self::new(name, size, extra, 0, Some(size), q)
    }
}

impl Stream for ContentStream {
    type Item = Result<Bytes, std::io::Error>;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.get_mut();
        if this.pos >= this.end {
            return Poll::Ready(None);
        }
        if this.fail_after > 0 && this.sent >= this.fail_after {
            // Close the connection abruptly without sending the remaining bytes.
            return Poll::Ready(None);
        }
        // Truncate relative to the requested range: a server that always
        // cuts short cuts every request, so resumes cannot silently complete.
        if this.truncated && this.sent > (this.end - this.req_start) / 2 {
            return Poll::Ready(None);
        }
        let want = ((this.end - this.pos) as usize).min(this.chunk);
        if want == 0 {
            return Poll::Ready(None);
        }
        if this.rate > 0 {
            // Test server only: a short synchronous sleep keeps pacing simple.
            let delay = Duration::from_secs_f64(want as f64 / this.rate as f64);
            std::thread::sleep(delay);
        }
        let mut buf = vec![0u8; want];
        this.rng.fill_bytes(&mut buf);
        this.pos += want as u64;
        this.sent += want as u64;
        let _ = cx.waker();
        Poll::Ready(Some(Ok(Bytes::from(buf))))
    }
}

/// Compute the SHA-256 of a fixture (full file) — used by tests and /hash.
pub fn content_sha256(name: &str, size: u64, extra: u64) -> String {
    let mut hasher = Sha256::new();
    let mut rng = ChaCha8Rng::from_seed(seed_for(name, size, extra));
    let mut remaining = size;
    let mut buf = vec![0u8; 1024 * 1024];
    while remaining > 0 {
        let n = remaining.min(buf.len() as u64) as usize;
        rng.fill_bytes(&mut buf[..n]);
        hasher.update(&buf[..n]);
        remaining -= n as u64;
    }
    hex::encode(hasher.finalize())
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

async fn file_hash(Path(name): Path<String>, Query(q): Query<Q>, State(st): State<ServerState>) -> Response {
    let size = fixture_size(&name);
    let extra = extra_for(&q, &st);
    let h = content_sha256(&name, size, extra);
    serde_json::json!({ "name": name, "size": size, "sha256": h }).to_string().into_response()
}

fn extra_for(q: &Q, st: &ServerState) -> u64 {
    if q.change.unwrap_or(false) {
        st.change_counter.fetch_add(1, Ordering::SeqCst)
    } else {
        0
    }
}

async fn redirect(Path(n): Path<u32>, Query(q): Query<Q>) -> Response {
    if n == 0 {
        return redirect_to_file(&q).into_response();
    }
    let next = format!("/redirect/{}", n - 1);
    let mut resp = Response::new(Body::empty());
    *resp.status_mut() = StatusCode::FOUND;
    resp.headers_mut()
        .insert(header::LOCATION, next.parse().unwrap());
    resp
}

async fn redirect_loop() -> Response {
    let mut resp = Response::new(Body::empty());
    *resp.status_mut() = StatusCode::FOUND;
    resp.headers_mut()
        .insert(header::LOCATION, "/redirect-loop".parse().unwrap());
    resp
}

fn redirect_to_file(q: &Q) -> Response {
    let mut resp = Response::new(Body::empty());
    *resp.status_mut() = StatusCode::FOUND;
    let target = if let Some(f) = &q.filename {
        format!("/file/{}", f)
    } else {
        "/file/small.bin".to_string()
    };
    resp.headers_mut()
        .insert(header::LOCATION, target.parse().unwrap());
    resp
}

async fn get_file(
    Path(name): Path<String>,
    Query(q): Query<Q>,
    State(st): State<ServerState>,
    headers: HeaderMap,
) -> Response {
    st.request_count.fetch_add(1, Ordering::SeqCst);
    let size = fixture_size(&name);
    let extra = extra_for(&q, &st);
    let etag = etag_for(&name, size, extra);

    // fail_first: the first *download* request to this path fails with the
    // given status; later requests succeed (used to test retry behavior).
    // `bytes=0-0` probes (engine probe + add-dialog preview) are not counted,
    // so the failing request is an actual segment/full-body download attempt.
    if let Some(status) = q.fail_first {
        let is_probe = headers
            .get(header::RANGE)
            .and_then(|v| v.to_str().ok())
            .map(|r| r.trim() == "bytes=0-0")
            .unwrap_or(false);
        if !is_probe {
            let key = format!("{name}?{}|ff", serde_json::to_string(&q).unwrap_or_default());
            let hit = st.record_hit(&key);
            if hit == 1 {
                let mut resp = Response::new(Body::empty());
                *resp.status_mut() =
                    StatusCode::from_u16(status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
                return resp;
            }
        }
    }

    if let Some(status) = q.status {
        let mut resp = Response::new(Body::empty());
        *resp.status_mut() = StatusCode::from_u16(status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
        if let Some(ra) = q.retry_after {
            resp.headers_mut()
                .insert(header::RETRY_AFTER, ra.to_string().parse().unwrap());
        }
        return resp;
    }

    // Auth check.
    if q.auth.unwrap_or(false) && !basic_auth_ok(&headers) {
        let mut resp = Response::new(Body::empty());
        *resp.status_mut() = StatusCode::UNAUTHORIZED;
        resp.headers_mut().insert(
            header::WWW_AUTHENTICATE,
            "Basic realm=\"test\"".parse().unwrap(),
        );
        return resp;
    }

    let mut resp = Response::new(Body::empty());
    resp.headers_mut()
        .insert(header::ETAG, etag.parse().unwrap());
    resp.headers_mut().insert(
        header::LAST_MODIFIED,
        "Wed, 21 Oct 2020 07:28:00 GMT".parse().unwrap(),
    );
    resp.headers_mut()
        .insert(header::CONTENT_TYPE, "application/octet-stream".parse().unwrap());
    if let Some(f) = &q.filename {
        resp.headers_mut().insert(
            header::CONTENT_DISPOSITION,
            format!("attachment; filename=\"{f}\"").parse().unwrap(),
        );
    }

    // Range handling.
    let range_header = headers.get(header::RANGE).and_then(|v| v.to_str().ok());
    let wants_range = range_header.is_some() && !q.no_range.unwrap_or(false);
    let parsed = range_header.and_then(parse_range);

    match (wants_range, parsed) {
        (true, Some((start, end))) => {
            let end = end.min(size - 1);
            let start = start.min(end);
            let len = end - start + 1;
            let mut body = ContentStream::new(&name, size, extra, start, Some(end + 1), &q);
            if q.over_send.unwrap_or(false) {
                // Send extra bytes beyond the requested range.
                body.end = (end + 1 + len).min(size);
            }
            *resp.status_mut() = StatusCode::PARTIAL_CONTENT;
            let cr = if q.wrong_range.unwrap_or(false) {
                format!("bytes 999999-{}/{}", 999999 + len - 1, size)
            } else {
                format!("bytes {start}-{end}/{size}")
            };
            resp.headers_mut()
                .insert(header::CONTENT_RANGE, cr.parse().unwrap());
            if !q.chunked.unwrap_or(false) {
                resp.headers_mut()
                    .insert(header::CONTENT_LENGTH, len.to_string().parse().unwrap());
            }
            resp.headers_mut().insert(header::ACCEPT_RANGES, "bytes".parse().unwrap());
            *resp.body_mut() = Body::from_stream(body);
            resp
        }
        _ => {
            if q.no_range.unwrap_or(false) {
                // Server claims it does not support ranges.
                resp.headers_mut()
                    .insert(header::ACCEPT_RANGES, "none".parse().unwrap());
            } else {
                resp.headers_mut()
                    .insert(header::ACCEPT_RANGES, "bytes".parse().unwrap());
            }
            if !q.chunked.unwrap_or(false) {
                resp.headers_mut()
                    .insert(header::CONTENT_LENGTH, size.to_string().parse().unwrap());
            }
            let body = ContentStream::full(&name, size, extra, &q);
            *resp.body_mut() = Body::from_stream(body);
            resp
        }
    }
}

fn parse_range(s: &str) -> Option<(u64, u64)> {
    let s = s.trim().strip_prefix("bytes=")?;
    let (a, b) = s.split_once('-')?;
    let start: u64 = a.trim().parse().ok()?;
    let end: u64 = if b.trim().is_empty() {
        u64::MAX
    } else {
        b.trim().parse().ok()?
    };
    Some((start, end))
}

fn basic_auth_ok(headers: &HeaderMap) -> bool {
    let Some(v) = headers.get(header::AUTHORIZATION).and_then(|v| v.to_str().ok()) else {
        return false;
    };
    let Some(rest) = v.strip_prefix("Basic ") else {
        return false;
    };
    use base64::Engine;
    let decoded = base64::engine::general_purpose::STANDARD
        .decode(rest)
        .unwrap_or_default();
    decoded == b"user:pass"
}

/// Convenience: run `f` with a fresh server, returning the base URL.
pub async fn with_server<F, T>(f: F) -> T
where
    F: FnOnce(String) -> T,
{
    let running = start().await;
    f(running.base_url)
}

/// Build a query string from key/value pairs.
pub fn qmap(v: &[(&str, &str)]) -> String {
    let mut s = String::new();
    for (i, (k, val)) in v.iter().enumerate() {
        if i > 0 {
            s.push('&');
        }
        s.push_str(k);
        s.push('=');
        s.push_str(val);
    }
    s
}
